server:
  servlet:
    context-path: /roomy
  port: 8080

spring:
  datasource:
    url: jdbc:h2:./roomydb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
